name: Gradle Build

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          ./gradlew build

      - name: List files
        run: ls

      - name: Publish jars
        uses: actions/upload-artifact@v4
        with:
          name: HeadlessMc
          path: |
            ./build/libs/headlessmc-launcher*.jar
            ./build/libs/headlessmc-lwjgl*.jar
            ./headlessmc-lwjgl/build/noasm/headlessmc-lwjgl-*-no-asm.jar
            ./headlessmc-scripts/hmc
            ./headlessmc-scripts/hmc.bat
